language: python

cache: pip

services:
- postgresql

matrix:
  include:
  - python: '3.6'
    env: 'AIOHTTP_VERSION=aiohttp==3.5.4'
  - python: '3.7'
    dist: xenial
    sudo: required
    env: 'AIOHTTP_VERSION=aiohttp==3.5.4'
  - python: '3.7'
    dist: xenial
    sudo: required
    env: 'AIOHTTP_VERSION=https://github.com/aio-libs/aiohttp/archive/master.zip'
  - python: '3.8'
    dist: xenial
    sudo: required
    env: 'AIOHTTP_VERSION=aiohttp==3.5.4'
  - python: '3.9'
    env: 'AIOHTTP_VERSION=aiohttp==3.5.4'

  allow_failures:
  - python: '3.9'
  - env: 'AIOHTTP_VERSION=https://github.com/aio-libs/aiohttp/archive/master.zip'

install:
- make install
- pip install -U "${AIOHTTP_VERSION}"
- pip freeze

script:
- make lint
- make test
- ./tests/check_tag.py
#- make docs
- pip freeze
- ls -lha

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: aio-libs-bot
  password:
    secure: >-
      pAzJhAD5HNzxvbNg/UwquwPXOp6V27gi4MpqCs6mK2Hy9h3Ii8vVWzEUx06v2aqT5b3P7FDBRW8+t9oL+aS/dZxeOtA/jNzROxMhFtRbpv1F/Mvd6ocz7yb3yg9WUlc7bhuyN6GUxsw4esATElQygqZucXRGsg+yauiTTd2X1CK6zrTz7/5lhF5H41oMzBKBZgvEUjDzaTs+C+B0bEifADVsI8QDa4EUTzCc93qf2z1jllDd/Jww9MK6xdBJJCoXjfBtWSjnoBANN/Ikthy8yY2PXvbLKH7K4Ri+ED72tLXThuTEsmquj20TnR30Hpm0LjwfdZ1+2O0X0PMyjMIRoATR0D9XdSP36FZs19zyRRFwHYKxZvXKSv+rZxz1rZYbbPojNW/498zlWcI8R9TxqPg/6dnrO1StnltLmN784AVBQr172CX/Ji3BF1bVytgdKqstGVN6d1JJWPuFVNfGpVHJJZEEuOBndK7yoSSV4zMva5wXplETVyGWfPiqvQCtylq8IatXbFxA0trCMW1kQEwBMBLbYrqx6ZIHQJ4Z46ng7OIYdRPod7fkK7e0lXU7OexfXad/UOWfkayOG1C93MWxeVho8ZQrBCdrHd1a5iujAfW8pk7Al8f2gS8L7nZTXUlkWK2ppX9PDOv1O0frtFc1prje+9AzROFC8UXxJk8=
  distributions: sdist bdist_wheel
  # skip_cleanup: true is required to include livereload.js
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
    condition: "$AIOHTTP_VERSION = aiohttp==3.5.4"
